name: Build LuckPerms for Akashic Server
# By Myth, created for Akashic Server


on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '00 18 * * *'


jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    
    - uses: actions/checkout@v2
      with:  
        fetch-depth: '0'

    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - uses: actions/upload-artifact@v2
      with:
        name: LuckPerms-Bukkit.jar
        path: bukkit/build/libs/LuckPerms*.jar

    - uses: actions/upload-artifact@v2
      with:
        name: LuckPerms-BungeeCord.jar
        path: bungee/build/libs/LuckPerms*.jar

    - uses: actions/upload-artifact@v2
      with:
        name: LuckPerms-Sponge.jar
        path: sponge/build/libs/LuckPerms*.jar

    - uses: actions/upload-artifact@v2
      with:
        name: LuckPerms-Nukkit.jar
        path: nukkit/build/libs/LuckPerms*.jar

    - uses: actions/upload-artifact@v2
      with:
        name: LuckPerms-Velocity.jar
        path: velocity/build/libs/LuckPerms*.jar

    - uses: actions/upload-artifact@v2
      with:
        name: LuckPerms-BukkitLegacy.jar
        path: bukkit-legacy/build/libs/LuckPerms*.jar